// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr-M7_tGPvyle1urT_WeAc0cG4WGJpai4',
    appId: '1:25840478730:web:d5434467585de9e9250df3',
    messagingSenderId: '25840478730',
    projectId: 'assignment3-fa00b',
    authDomain: 'assignment3-fa00b.firebaseapp.com',
    storageBucket: 'assignment3-fa00b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSzNG3hq_QMM2Bq3AsPfWoKefEZsVrQk',
    appId: '1:25840478730:android:5226b1cf09075eaf250df3',
    messagingSenderId: '25840478730',
    projectId: 'assignment3-fa00b',
    storageBucket: 'assignment3-fa00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63q2NswqEm4mdSkTpvdQ7QCRiolSJSyE',
    appId: '1:25840478730:ios:cf1b608dea8616f4250df3',
    messagingSenderId: '25840478730',
    projectId: 'assignment3-fa00b',
    storageBucket: 'assignment3-fa00b.appspot.com',
    androidClientId: '25840478730-q8fjndvm7k2hnfpkur75dv9vsqhmnuk3.apps.googleusercontent.com',
    iosClientId: '25840478730-a5sbvrkgahonut24ab8cacmk59u3d5bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentThree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD63q2NswqEm4mdSkTpvdQ7QCRiolSJSyE',
    appId: '1:25840478730:ios:2f1a55942b483f74250df3',
    messagingSenderId: '25840478730',
    projectId: 'assignment3-fa00b',
    storageBucket: 'assignment3-fa00b.appspot.com',
    androidClientId: '25840478730-q8fjndvm7k2hnfpkur75dv9vsqhmnuk3.apps.googleusercontent.com',
    iosClientId: '25840478730-lofmm5bi3c8f73kvv2nosg82bsl0akti.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentThree.RunnerTests',
  );
}
